ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  dingtalk-robot:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 钉小弟 - 钉钉群机器人
      Role: 'acs:ram::1348483923043559:role/AliyunFcDefaultRole'
      LogConfig:
        Project: dingtalk-robot-log
        Logstore: dingtalk-robot-log
      InternetAccess: true
    dingtalk-robot-fc:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        Timeout: 120
        MemorySize: 1024
        InstanceConcurrency: 5
        EnvironmentVariables:
          LD_LIBRARY_PATH: >-
            /code/.fun/root/usr/local/lib:/code/.fun/root/usr/lib:/code/.fun/root/usr/lib/x86_64-linux-gnu:/code/.fun/root/usr/lib64:/code/.fun/root/lib:/code/.fun/root/lib/x86_64-linux-gnu:/code/.fun/root/python/lib/python2.7/site-packages:/code/.fun/root/python/lib/python3.6/site-packages:/code:/code/lib:/usr/local/lib
          NODE_PATH: '/code/node_modules:/usr/local/lib/node_modules'
          PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code:/code/node_modules/.bin:/code/.fun/python/bin:/code/.fun/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin
          PYTHONUSERBASE: /code/.fun/python
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            Qualifier: prod
            AuthType: anonymous
            Methods:
              - GET
              - POST
        httpTrigger-dev:
          Type: HTTP
          Properties:
            Qualifier: LATEST
            AuthType: anonymous
            Methods:
              - GET
              - POST
