ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  dingtalk-robot:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: 钉小弟 - 钉钉群机器人
      Role: 'acs:ram::1348483923043559:role/AliyunFcDefaultRole'
      InternetAccess: true
    baidutj:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs12
        Timeout: 20
        MemorySize: 256
        InstanceConcurrency: 1
        EnvironmentVariables: {}
      Events:
        baidutj:
          Type: Timer
          Properties:
            Qualifier: LATEST
            CronExpression: '0 0 2,7,13 * * ?'
            Enable: true
    dingtalk-robot-fc:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: custom
        Timeout: 120
        MemorySize: 256
        InstanceConcurrency: 5
        EnvironmentVariables:
          LD_LIBRARY_PATH: >-
            /code/.fun/root/usr/local/lib:/code/.fun/root/usr/lib:/code/.fun/root/usr/lib/x86_64-linux-gnu:/code/.fun/root/usr/lib64:/code/.fun/root/lib:/code/.fun/root/lib/x86_64-linux-gnu:/code/.fun/root/python/lib/python2.7/site-packages:/code/.fun/root/python/lib/python3.6/site-packages:/code:/code/lib:/usr/local/lib
          NODE_PATH: '/code/node_modules:/usr/local/lib/node_modules'
          PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code:/code/node_modules/.bin:/code/.fun/python/bin:/code/.fun/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin
          PYTHONUSERBASE: /code/.fun/python
      Events:
        httpTrigger:
          Type: HTTP
          Properties:
            Qualifier: prod
            AuthType: anonymous
            Methods:
              - GET
              - POST
        httpTrigger-dev:
          Type: HTTP
          Properties:
            Qualifier: LATEST
            AuthType: anonymous
            Methods:
              - GET
              - POST
    jizhangla:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs12
        Timeout: 20
        MemorySize: 256
        InstanceConcurrency: 1
        EnvironmentVariables: {}
      Events:
        jizhangla:
          Type: Timer
          Properties:
            Qualifier: LATEST
            CronExpression: 0 20 0 * * ?
            Enable: true
    money:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs12
        Timeout: 20
        MemorySize: 256
        InstanceConcurrency: 1
        EnvironmentVariables: {}
      Events:
        money:
          Type: Timer
          Properties:
            Qualifier: LATEST
            CronExpression: '0 30 1,3,5,6 ? * MON-FRI'
            Enable: true
    refresh-fc:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs12
        Timeout: 20
        MemorySize: 128
        InstanceConcurrency: 1
        EnvironmentVariables: {}
      Events:
        refresh-fc:
          Type: Timer
          Properties:
            Qualifier: LATEST
            CronExpression: '@every 2m'
            Enable: true
